# HR Analytics Dashboard
### Dataset: IBM HR Analytics Employee Attrition

**Author:** Mohamed Arsath A| B.Tech AI & Data Science  
**Dataset:** IBM HR Analytics Employee Attrition — Kaggle  
**Tools:** Python, Pandas, MySQL, SQL, Power BI  

###  Project Overview
This project analyzes **1,470 employee records** from IBM's HR dataset.  
We explore attrition patterns, employee satisfaction, salary trends, and identify **high-risk employees** using SQL queries.  
The final output is a **4-page interactive Power BI Dashboard** connected directly to MySQL.

---

###  Business Problem
Employee attrition costs companies **33% of an employee's annual salary** in replacement costs.  
HR teams need data-driven insights to identify **why employees leave** and **who is at risk** of leaving.

---

###  Key Questions 
1. What is the overall attrition rate?
2. Which department has the highest attrition?
3. Does overtime cause attrition?
4. Which salary band has highest exit rate?
5. Who are the high-risk employees?
6. What is the impact of job satisfaction on attrition?

##  Step 1: Install & Import Libraries

In [1]:
import sys
!{sys.executable} -m pip install pandas numpy sqlalchemy mysql-connector-python ipython-sql

Requirement already satisfied: pandas in .\env\lib\site-packages (2.0.3)
Requirement already satisfied: numpy in .\env\lib\site-packages (1.24.4)
Requirement already satisfied: sqlalchemy in .\env\lib\site-packages (2.0.45)
Requirement already satisfied: mysql-connector-python in .\env\lib\site-packages (9.0.0)
Requirement already satisfied: ipython-sql in .\env\lib\site-packages (0.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\env\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.1 in .\env\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: typing-extensions>=4.6.0 in .\env\lib\site-packages (from sqlalchemy) (4.13.2)
Requirement already satisfied: greenlet>=1 in .\env\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: prettytable in .\env\lib\site-packages (from ipython-sql) (0.7.2)
Requirement already satisfied: ipython in .\env\lib\site-packages (from ipython-sql) (8.12.3)
Requirement already satisfied: sqlparse in .\env\lib\site-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in .\env\lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in .\env\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: backcall in .\env\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: decorator in .\env\lib\site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: jedi>=0.16 in .\env\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in .\env\lib\site-packages (from ipython->ipython-sql) (0.1.7)
Requirement already satisfied: pickleshare in .\env\lib\site-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in .\env\lib\site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in .\env\lib\site-packages (from ipython->ipython-sql) (2.19.2)
Requirement already satisfied: stack-data in .\env\lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5 in .\env\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in .\env\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in .\env\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.5)
Requirement already satisfied: wcwidth in .\env\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython->ipython-sql) (0.2.14)
Requirement already satisfied: executing>=1.2.0 in .\env\lib\site-packages (from stack-data->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in .\env\lib\site-packages (from stack-data->ipython->ipython-sql) (3.0.1)
Requirement already satisfied: pure-eval in .\env\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.3)

In [2]:
# Import all libraries
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import warnings
warnings.filterwarnings('ignore')

print("✅ All libraries imported successfully!")

✅ All libraries imported successfully!

---
## Step 2: Load Dataset

In [3]:
df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

print("✅ Dataset Loaded Successfully!")
print(f"📊 Shape: {df.shape[0]} rows × {df.shape[1]} columns")

✅ Dataset Loaded Successfully!
📊 Shape: 1470 rows × 35 columns

In [4]:
# Preview first 5 rows
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [5]:
# Check all column names
print("📋 All Columns:")
print(list(df.columns))

📋 All Columns:
['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

In [6]:
# Check data types and info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [7]:
# Basic statistics
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

---
##  Step 3: Connect to MySQL & Push Data

In [9]:
%load_ext sql
%sql mysql+mysqlconnector://root:root@localhost/test

In [10]:
# Create MySQL engine
# Format: mysql+mysqlconnector://username:password@host/database

engine = create_engine('mysql+mysqlconnector://root:root@localhost/hr_analytics')

# Push dataframe to MySQL
df.to_sql('hr_data', con=engine, if_exists='replace', index=False)

print("✅ Data pushed to MySQL successfully!")
print(f"📊 Total rows loaded: {len(df)}")

✅ Data pushed to MySQL successfully!
📊 Total rows loaded: 1470

In [14]:
%%sql
show databases;

 * mysql+mysqlconnector://root:***@localhost/test
11 rows affected.

[('de_project',),
 ('demo',),
 ('hr_analytics',),
 ('information_schema',),
 ('mysql',),
 ('performance_schema',),
 ('sakila',),
 ('sys',),
 ('test',),
 ('uber',),
 ('world',)]

In [15]:
%%sql
use hr_analytics

 * mysql+mysqlconnector://root:***@localhost/test
0 rows affected.

[]

In [16]:
%%sql
-- Verify data loaded correctly
SELECT COUNT(*) AS Total_Records FROM hr_data;

 * mysql+mysqlconnector://root:***@localhost/test
1 rows affected.

[(1470,)]

##  Step 4: Data Cleaning & Validation

In [17]:
%%sql
-- Check NULL values in all key columns
SELECT
    SUM(CASE WHEN Age IS NULL THEN 1 ELSE 0 END)            AS Null_Age,
    SUM(CASE WHEN Attrition IS NULL THEN 1 ELSE 0 END)      AS Null_Attrition,
    SUM(CASE WHEN Department IS NULL THEN 1 ELSE 0 END)     AS Null_Department,
    SUM(CASE WHEN MonthlyIncome IS NULL THEN 1 ELSE 0 END)  AS Null_Income,
    SUM(CASE WHEN JobRole IS NULL THEN 1 ELSE 0 END)        AS Null_JobRole,
    SUM(CASE WHEN OverTime IS NULL THEN 1 ELSE 0 END)       AS Null_OverTime
FROM hr_data;

 * mysql+mysqlconnector://root:***@localhost/test
1 rows affected.

[(Decimal('0'), Decimal('0'), Decimal('0'), Decimal('0'), Decimal('0'), Decimal('0'))]

In [18]:
%%sql
-- Check distinct departments
SELECT DISTINCT Department FROM hr_data;

 * mysql+mysqlconnector://root:***@localhost/test
3 rows affected.

[('Sales',), ('Research & Development',), ('Human Resources',)]

In [19]:
%%sql
-- Check distinct job roles
SELECT DISTINCT JobRole FROM hr_data;

 * mysql+mysqlconnector://root:***@localhost/test
9 rows affected.

[('Sales Executive',),
 ('Research Scientist',),
 ('Laboratory Technician',),
 ('Manufacturing Director',),
 ('Healthcare Representative',),
 ('Manager',),
 ('Sales Representative',),
 ('Research Director',),
 ('Human Resources',)]

In [20]:
%%sql
-- Check attrition values
SELECT 
    Attrition,
    COUNT(*) AS Count
FROM hr_data
GROUP BY Attrition;

 * mysql+mysqlconnector://root:***@localhost/test
2 rows affected.

[('Yes', 237), ('No', 1233)]

##  Step 5: Feature Engineering — Add New Columns

In [21]:
%%sql
-- Add Age Group column
ALTER TABLE hr_data ADD COLUMN AgeGroup VARCHAR(20);

 * mysql+mysqlconnector://root:***@localhost/test
0 rows affected.

[]

In [22]:
%%sql
-- Update Age Group values
UPDATE hr_data SET AgeGroup =
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '55+'
    END;

 * mysql+mysqlconnector://root:***@localhost/test
1470 rows affected.

[]

In [23]:
%%sql
-- Add Salary Band column
ALTER TABLE hr_data ADD COLUMN SalaryBand VARCHAR(20);

 * mysql+mysqlconnector://root:***@localhost/test
0 rows affected.

[]

In [24]:
%%sql
-- Update Salary Band values
UPDATE hr_data SET SalaryBand =
    CASE
        WHEN MonthlyIncome < 3000                  THEN 'Low (<3K)'
        WHEN MonthlyIncome BETWEEN 3000 AND 6000   THEN 'Medium (3K-6K)'
        WHEN MonthlyIncome BETWEEN 6001 AND 10000  THEN 'High (6K-10K)'
        ELSE 'Very High (>10K)'
    END;

 * mysql+mysqlconnector://root:***@localhost/test
1470 rows affected.

[]

In [25]:
%%sql
-- Add Experience Band column
ALTER TABLE hr_data ADD COLUMN ExperienceBand VARCHAR(20);

 * mysql+mysqlconnector://root:***@localhost/test
0 rows affected.

[]

In [26]:
%%sql
-- Update Experience Band values
UPDATE hr_data SET ExperienceBand =
    CASE
        WHEN TotalWorkingYears BETWEEN 0  AND 5  THEN '0-5 Years'
        WHEN TotalWorkingYears BETWEEN 6  AND 10 THEN '6-10 Years'
        WHEN TotalWorkingYears BETWEEN 11 AND 20 THEN '11-20 Years'
        ELSE '20+ Years'
    END;

 * mysql+mysqlconnector://root:***@localhost/test
1470 rows affected.

[]

In [27]:
%%sql
-- Add Education Label column
ALTER TABLE hr_data ADD COLUMN EducationLabel VARCHAR(20);

 * mysql+mysqlconnector://root:***@localhost/test
0 rows affected.

[]

In [28]:
%%sql
-- Update Education Label values
UPDATE hr_data SET EducationLabel =
    CASE Education
        WHEN 1 THEN 'Below College'
        WHEN 2 THEN 'College'
        WHEN 3 THEN 'Bachelor'
        WHEN 4 THEN 'Master'
        WHEN 5 THEN 'Doctor'
    END;

 * mysql+mysqlconnector://root:***@localhost/test
1470 rows affected.

[]

In [29]:
%%sql
-- Add Attrition Risk column
ALTER TABLE hr_data ADD COLUMN AttritionRisk VARCHAR(15);

 * mysql+mysqlconnector://root:***@localhost/test
0 rows affected.

[]

In [30]:
%%sql
-- Update Attrition Risk values
UPDATE hr_data SET AttritionRisk =
    CASE
        WHEN JobSatisfaction <= 2
         AND WorkLifeBalance <= 2
         AND OverTime = 'Yes'  THEN 'HIGH RISK'
        WHEN JobSatisfaction = 3
         AND OverTime = 'Yes'  THEN 'MEDIUM RISK'
        ELSE 'LOW RISK'
    END;

 * mysql+mysqlconnector://root:***@localhost/test
1470 rows affected.

[]

In [31]:
%%sql
-- Verify all new columns added
SELECT
    EmployeeNumber,
    Age, AgeGroup,
    MonthlyIncome, SalaryBand,
    TotalWorkingYears, ExperienceBand,
    EducationLabel,
    AttritionRisk
FROM hr_data
LIMIT 10;

 * mysql+mysqlconnector://root:***@localhost/test
10 rows affected.

[(1, 41, '36-45', 5993, 'Medium (3K-6K)', 8, '6-10 Years', 'College', 'LOW RISK'),
 (2, 49, '46-55', 5130, 'Medium (3K-6K)', 10, '6-10 Years', 'Below College', 'LOW RISK'),
 (4, 37, '36-45', 2090, 'Low (<3K)', 7, '6-10 Years', 'College', 'MEDIUM RISK'),
 (5, 33, '26-35', 2909, 'Low (<3K)', 8, '6-10 Years', 'Master', 'MEDIUM RISK'),
 (7, 27, '26-35', 3468, 'Medium (3K-6K)', 6, '6-10 Years', 'Below College', 'LOW RISK'),
 (8, 32, '26-35', 3068, 'Medium (3K-6K)', 8, '6-10 Years', 'College', 'LOW RISK'),
 (10, 59, '55+', 2670, 'Low (<3K)', 12, '11-20 Years', 'Bachelor', 'HIGH RISK'),
 (11, 30, '26-35', 2693, 'Low (<3K)', 1, '0-5 Years', 'Below College', 'LOW RISK'),
 (12, 38, '36-45', 9526, 'High (6K-10K)', 10, '6-10 Years', 'Bachelor', 'LOW RISK'),
 (13, 36, '36-45', 5237, 'Medium (3K-6K)', 17, '11-20 Years', 'Bachelor', 'LOW RISK')]

##  Step 6: KPI Analysis

In [32]:
%%sql
-- Overall KPI Summary
SELECT
    COUNT(*)                                                                      AS Total_Employees,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Total_Attrition,
    SUM(CASE WHEN Attrition='No'  THEN 1 ELSE 0 END)                            AS Active_Employees,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate_Pct,
    ROUND(AVG(Age),1)                                                             AS Avg_Age,
    ROUND(AVG(MonthlyIncome),0)                                                  AS Avg_Monthly_Income,
    ROUND(AVG(JobSatisfaction),2)                                                AS Avg_Job_Satisfaction,
    ROUND(AVG(YearsAtCompany),1)                                                 AS Avg_Tenure_Years,
    SUM(CASE WHEN OverTime='Yes' THEN 1 ELSE 0 END)                             AS Total_OT_Employees
FROM hr_data;

 * mysql+mysqlconnector://root:***@localhost/test
1 rows affected.

[(1470, Decimal('237'), Decimal('1233'), Decimal('16.12'), Decimal('36.9'), Decimal('6503'), Decimal('2.73'), Decimal('7.0'), Decimal('416'))]

##  Step 7: Attrition Analysis

In [33]:
%%sql
-- Attrition by Department
SELECT
    Department,
    COUNT(*)                                                                      AS Total,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Attrition_Count,
    SUM(CASE WHEN Attrition='No'  THEN 1 ELSE 0 END)                            AS Active_Count,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate
FROM hr_data
GROUP BY Department
ORDER BY Attrition_Rate DESC;

 * mysql+mysqlconnector://root:***@localhost/test
3 rows affected.

[('Sales', 446, Decimal('92'), Decimal('354'), Decimal('20.63')),
 ('Human Resources', 63, Decimal('12'), Decimal('51'), Decimal('19.05')),
 ('Research & Development', 961, Decimal('133'), Decimal('828'), Decimal('13.84'))]

In [34]:
%%sql
-- Attrition by Job Role
SELECT
    JobRole,
    COUNT(*)                                                                      AS Total,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Attrition_Count,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate,
    ROUND(AVG(MonthlyIncome),0)                                                  AS Avg_Salary
FROM hr_data
GROUP BY JobRole
ORDER BY Attrition_Rate DESC;

 * mysql+mysqlconnector://root:***@localhost/test
9 rows affected.

[('Sales Representative', 83, Decimal('33'), Decimal('39.76'), Decimal('2626')),
 ('Laboratory Technician', 259, Decimal('62'), Decimal('23.94'), Decimal('3237')),
 ('Human Resources', 52, Decimal('12'), Decimal('23.08'), Decimal('4236')),
 ('Sales Executive', 326, Decimal('57'), Decimal('17.48'), Decimal('6924')),
 ('Research Scientist', 292, Decimal('47'), Decimal('16.10'), Decimal('3240')),
 ('Manufacturing Director', 145, Decimal('10'), Decimal('6.90'), Decimal('7295')),
 ('Healthcare Representative', 131, Decimal('9'), Decimal('6.87'), Decimal('7529')),
 ('Manager', 102, Decimal('5'), Decimal('4.90'), Decimal('17182')),
 ('Research Director', 80, Decimal('2'), Decimal('2.50'), Decimal('16034'))]

In [35]:
%%sql
-- Attrition by Age Group
SELECT
    AgeGroup,
    COUNT(*)                                                                      AS Total,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Attrition_Count,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate
FROM hr_data
GROUP BY AgeGroup
ORDER BY AgeGroup;

 * mysql+mysqlconnector://root:***@localhost/test
5 rows affected.

[('18-25', 123, Decimal('44'), Decimal('35.77')),
 ('26-35', 606, Decimal('116'), Decimal('19.14')),
 ('36-45', 468, Decimal('43'), Decimal('9.19')),
 ('46-55', 226, Decimal('26'), Decimal('11.50')),
 ('55+', 47, Decimal('8'), Decimal('17.02'))]

In [36]:
%%sql
-- Attrition by Gender
SELECT
    Gender,
    COUNT(*)                                                                      AS Total,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Attrition_Count,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate
FROM hr_data
GROUP BY Gender;

 * mysql+mysqlconnector://root:***@localhost/test
2 rows affected.

[('Female', 588, Decimal('87'), Decimal('14.80')),
 ('Male', 882, Decimal('150'), Decimal('17.01'))]

In [37]:
%%sql
-- Attrition by Salary Band
SELECT
    SalaryBand,
    COUNT(*)                                                                      AS Total,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Attrition_Count,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate
FROM hr_data
GROUP BY SalaryBand
ORDER BY Attrition_Rate DESC;

 * mysql+mysqlconnector://root:***@localhost/test
4 rows affected.

[('Low (<3K)', 395, Decimal('113'), Decimal('28.61')),
 ('Medium (3K-6K)', 519, Decimal('66'), Decimal('12.72')),
 ('High (6K-10K)', 275, Decimal('33'), Decimal('12.00')),
 ('Very High (>10K)', 281, Decimal('25'), Decimal('8.90'))]

In [38]:
%%sql
-- Attrition by OverTime (KEY BUSINESS INSIGHT)
SELECT
    OverTime,
    COUNT(*)                                                                      AS Total,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Attrition_Count,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate
FROM hr_data
GROUP BY OverTime;

 * mysql+mysqlconnector://root:***@localhost/test
2 rows affected.

[('Yes', 416, Decimal('127'), Decimal('30.53')),
 ('No', 1054, Decimal('110'), Decimal('10.44'))]

In [39]:
%%sql
-- Attrition by Marital Status
SELECT
    MaritalStatus,
    COUNT(*)                                                                      AS Total,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Attrition_Count,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate
FROM hr_data
GROUP BY MaritalStatus
ORDER BY Attrition_Rate DESC;

 * mysql+mysqlconnector://root:***@localhost/test
3 rows affected.

[('Single', 470, Decimal('120'), Decimal('25.53')),
 ('Married', 673, Decimal('84'), Decimal('12.48')),
 ('Divorced', 327, Decimal('33'), Decimal('10.09'))]

In [40]:
%%sql
-- Attrition by Business Travel
SELECT
    BusinessTravel,
    COUNT(*)                                                                      AS Total,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Attrition_Count,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate
FROM hr_data
GROUP BY BusinessTravel
ORDER BY Attrition_Rate DESC;

 * mysql+mysqlconnector://root:***@localhost/test
3 rows affected.

[('Travel_Frequently', 277, Decimal('69'), Decimal('24.91')),
 ('Travel_Rarely', 1043, Decimal('156'), Decimal('14.96')),
 ('Non-Travel', 150, Decimal('12'), Decimal('8.00'))]

##  Step 8: Satisfaction Analysis

In [41]:
%%sql
-- Satisfaction Scores by Department
SELECT
    Department,
    ROUND(AVG(JobSatisfaction),2)           AS Avg_Job_Satisfaction,
    ROUND(AVG(EnvironmentSatisfaction),2)   AS Avg_Env_Satisfaction,
    ROUND(AVG(RelationshipSatisfaction),2)  AS Avg_Relationship_Satisfaction,
    ROUND(AVG(WorkLifeBalance),2)           AS Avg_WorkLife_Balance
FROM hr_data
GROUP BY Department;

 * mysql+mysqlconnector://root:***@localhost/test
3 rows affected.

[('Sales', Decimal('2.75'), Decimal('2.68'), Decimal('2.70'), Decimal('2.82')),
 ('Research & Development', Decimal('2.73'), Decimal('2.74'), Decimal('2.71'), Decimal('2.73')),
 ('Human Resources', Decimal('2.60'), Decimal('2.68'), Decimal('2.89'), Decimal('2.92'))]

In [42]:
%%sql
-- Job Satisfaction vs Attrition
SELECT
    JobSatisfaction,
    COUNT(*)                                                                      AS Total,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Attrition_Count,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate
FROM hr_data
GROUP BY JobSatisfaction
ORDER BY JobSatisfaction;

 * mysql+mysqlconnector://root:***@localhost/test
4 rows affected.

[(1, 289, Decimal('66'), Decimal('22.84')),
 (2, 280, Decimal('46'), Decimal('16.43')),
 (3, 442, Decimal('73'), Decimal('16.52')),
 (4, 459, Decimal('52'), Decimal('11.33'))]

In [43]:
%%sql
-- Work Life Balance vs Attrition
SELECT
    WorkLifeBalance,
    COUNT(*)                                                                      AS Total,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Attrition_Count,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate
FROM hr_data
GROUP BY WorkLifeBalance
ORDER BY WorkLifeBalance;

 * mysql+mysqlconnector://root:***@localhost/test
4 rows affected.

[(1, 80, Decimal('25'), Decimal('31.25')),
 (2, 344, Decimal('58'), Decimal('16.86')),
 (3, 893, Decimal('127'), Decimal('14.22')),
 (4, 153, Decimal('27'), Decimal('17.65'))]

##  Step 9: Salary Analysis

In [44]:
%%sql
-- Salary by Department and Job Role
SELECT
    Department,
    JobRole,
    COUNT(*)                         AS Headcount,
    ROUND(AVG(MonthlyIncome),0)     AS Avg_Salary,
    MIN(MonthlyIncome)              AS Min_Salary,
    MAX(MonthlyIncome)              AS Max_Salary,
    ROUND(AVG(PercentSalaryHike),1) AS Avg_Hike_Pct
FROM hr_data
GROUP BY Department, JobRole
ORDER BY Department, Avg_Salary DESC;

 * mysql+mysqlconnector://root:***@localhost/test
11 rows affected.

[('Human Resources', 'Manager', 11, Decimal('18089'), 14026, 19717, Decimal('14.5')),
 ('Human Resources', 'Human Resources', 52, Decimal('4236'), 1555, 10725, Decimal('14.8')),
 ('Research & Development', 'Manager', 54, Decimal('17130'), 11244, 19999, Decimal('14.9')),
 ('Research & Development', 'Research Director', 80, Decimal('16034'), 11031, 19973, Decimal('15.0')),
 ('Research & Development', 'Healthcare Representative', 131, Decimal('7529'), 4000, 13966, Decimal('15.5')),
 ('Research & Development', 'Manufacturing Director', 145, Decimal('7295'), 4011, 13973, Decimal('15.6')),
 ('Research & Development', 'Research Scientist', 292, Decimal('3240'), 1009, 9724, Decimal('15.4')),
 ('Research & Development', 'Laboratory Technician', 259, Decimal('3237'), 1102, 7403, Decimal('15.0')),
 ('Sales', 'Manager', 37, Decimal('16987'), 11557, 19847, Decimal('15.6')),
 ('Sales', 'Sales Executive', 326, Decimal('6924'), 4001, 13872, Decimal('14.9')),
 ('Sales', 'Sales Representative', 83, Decimal('2626'), 1052, 6632, Decimal('15.7'))]

In [45]:
%%sql
-- Performance Rating vs Salary Hike
SELECT
    PerformanceRating,
    COUNT(*)                         AS Headcount,
    ROUND(AVG(PercentSalaryHike),1) AS Avg_Hike_Pct,
    ROUND(AVG(MonthlyIncome),0)     AS Avg_Salary
FROM hr_data
GROUP BY PerformanceRating
ORDER BY PerformanceRating;

 * mysql+mysqlconnector://root:***@localhost/test
2 rows affected.

[(3, 1244, Decimal('14.0'), Decimal('6537')),
 (4, 226, Decimal('21.8'), Decimal('6314'))]

##  Step 10: Advanced Analysis

In [47]:
%%sql
-- High Risk Employees Table
SELECT
    EmployeeNumber,
    Age,
    Department,
    JobRole,
    MonthlyIncome,
    JobSatisfaction,
    WorkLifeBalance,
    OverTime,
    YearsAtCompany,
    YearsSinceLastPromotion,
    Attrition,
    AttritionRisk
FROM hr_data
WHERE AttritionRisk IN ('HIGH RISK','MEDIUM RISK')
ORDER BY AttritionRisk, JobSatisfaction limit 10;

 * mysql+mysqlconnector://root:***@localhost/test
10 rows affected.

[(1998, 42, 'Research & Development', 'Research Scientist', 5410, 1, 2, 'Yes', 4, 1, 'No', 'HIGH RISK'),
 (454, 29, 'Research & Development', 'Laboratory Technician', 2119, 1, 2, 'Yes', 7, 0, 'Yes', 'HIGH RISK'),
 (10, 59, 'Research & Development', 'Laboratory Technician', 2670, 1, 2, 'Yes', 1, 0, 'No', 'HIGH RISK'),
 (68, 44, 'Sales', 'Sales Executive', 5454, 1, 2, 'Yes', 4, 1, 'No', 'HIGH RISK'),
 (605, 42, 'Research & Development', 'Manufacturing Director', 7406, 1, 2, 'Yes', 10, 5, 'No', 'HIGH RISK'),
 (267, 37, 'Research & Development', 'Research Scientist', 3564, 1, 2, 'Yes', 8, 1, 'No', 'HIGH RISK'),
 (802, 37, 'Research & Development', 'Research Scientist', 2782, 1, 2, 'Yes', 5, 4, 'No', 'HIGH RISK'),
 (124, 46, 'Research & Development', 'Healthcare Representative', 10673, 1, 2, 'Yes', 10, 9, 'No', 'HIGH RISK'),
 (932, 39, 'Research & Development', 'Laboratory Technician', 2404, 1, 1, 'Yes', 2, 2, 'Yes', 'HIGH RISK'),
 (1015, 30, 'Research & Development', 'Research Director', 11416, 1, 2, 'Yes', 8, 1, 'No', 'HIGH RISK')]

In [48]:
%%sql
-- Departments Above Company Average Attrition (Using CTE)
WITH company_avg AS (
    SELECT ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2) AS avg_rate
    FROM hr_data
)
SELECT
    h.Department,
    COUNT(*)                                                                      AS Total,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Dept_Rate,
    c.avg_rate                                                                    AS Company_Avg,
    CASE
        WHEN ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2) > c.avg_rate
        THEN '⚠ ACTION NEEDED'
        ELSE '✅ HEALTHY'
    END AS Status
FROM hr_data h, company_avg c
GROUP BY h.Department, c.avg_rate
ORDER BY Dept_Rate DESC;

 * mysql+mysqlconnector://root:***@localhost/test
3 rows affected.

[('Sales', 446, Decimal('20.63'), Decimal('16.12'), '⚠ ACTION NEEDED'),
 ('Human Resources', 63, Decimal('19.05'), Decimal('16.12'), '⚠ ACTION NEEDED'),
 ('Research & Development', 961, Decimal('13.84'), Decimal('16.12'), '✅ HEALTHY')]

In [49]:
%%sql
-- Promotion Gap Analysis
SELECT
    Department,
    JobRole,
    ROUND(AVG(YearsSinceLastPromotion),1)            AS Avg_Years_No_Promotion,
    COUNT(*)                                          AS Headcount,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END) AS Attrition_Count
FROM hr_data
GROUP BY Department, JobRole
HAVING Avg_Years_No_Promotion > 3
ORDER BY Avg_Years_No_Promotion DESC;

 * mysql+mysqlconnector://root:***@localhost/test
4 rows affected.

[('Research & Development', 'Manager', Decimal('5.5'), 54, Decimal('3')),
 ('Human Resources', 'Manager', Decimal('4.2'), 11, Decimal('0')),
 ('Sales', 'Manager', Decimal('4.1'), 37, Decimal('2')),
 ('Research & Development', 'Research Director', Decimal('3.2'), 80, Decimal('2'))]

In [50]:
%%sql
-- Training Impact on Attrition
SELECT
    TrainingTimesLastYear,
    COUNT(*)                                                                      AS Total,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Attrition_Count,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate
FROM hr_data
GROUP BY TrainingTimesLastYear
ORDER BY TrainingTimesLastYear;

 * mysql+mysqlconnector://root:***@localhost/test
7 rows affected.

[(0, 54, Decimal('15'), Decimal('27.78')),
 (1, 71, Decimal('9'), Decimal('12.68')),
 (2, 547, Decimal('98'), Decimal('17.92')),
 (3, 491, Decimal('69'), Decimal('14.05')),
 (4, 123, Decimal('26'), Decimal('21.14')),
 (5, 119, Decimal('14'), Decimal('11.76')),
 (6, 65, Decimal('6'), Decimal('9.23'))]

##  Step 11: Create SQL Views for Power BI

In [51]:
%%sql
-- View 1: Main Dashboard View (Connect this to Power BI)
CREATE OR REPLACE VIEW vw_hr_main AS
SELECT
    EmployeeNumber, Age, AgeGroup, Gender, MaritalStatus,
    Department, JobRole, JobLevel,
    MonthlyIncome, SalaryBand, PercentSalaryHike,
    JobSatisfaction, EnvironmentSatisfaction,
    RelationshipSatisfaction, WorkLifeBalance,
    OverTime, BusinessTravel, DistanceFromHome,
    TotalWorkingYears, ExperienceBand,
    YearsAtCompany, YearsInCurrentRole,
    YearsSinceLastPromotion, YearsWithCurrManager,
    TrainingTimesLastYear, PerformanceRating,
    EducationLabel, EducationField,
    Attrition, AttritionRisk
FROM hr_data;

 * mysql+mysqlconnector://root:***@localhost/test
0 rows affected.

[]

In [52]:
%%sql
-- View 2: KPI Summary View
CREATE OR REPLACE VIEW vw_kpi_summary AS
SELECT
    COUNT(*)                                                                      AS Total_Employees,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Total_Attrition,
    SUM(CASE WHEN Attrition='No'  THEN 1 ELSE 0 END)                            AS Active_Employees,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate,
    ROUND(AVG(Age),1)                                                             AS Avg_Age,
    ROUND(AVG(MonthlyIncome),0)                                                  AS Avg_Income,
    ROUND(AVG(JobSatisfaction),2)                                                AS Avg_Satisfaction,
    ROUND(AVG(YearsAtCompany),1)                                                 AS Avg_Tenure,
    SUM(CASE WHEN OverTime='Yes' THEN 1 ELSE 0 END)                             AS OT_Employees
FROM hr_data;

 * mysql+mysqlconnector://root:***@localhost/test
0 rows affected.

[]

In [53]:
%%sql
-- View 3: Department Summary View
CREATE OR REPLACE VIEW vw_dept_summary AS
SELECT
    Department,
    COUNT(*)                                                                      AS Total_Employees,
    SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)                            AS Attrition_Count,
    ROUND(SUM(CASE WHEN Attrition='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),2)    AS Attrition_Rate,
    ROUND(AVG(MonthlyIncome),0)                                                  AS Avg_Salary,
    ROUND(AVG(JobSatisfaction),2)                                                AS Avg_Satisfaction,
    ROUND(AVG(WorkLifeBalance),2)                                                AS Avg_WLB,
    SUM(CASE WHEN OverTime='Yes' THEN 1 ELSE 0 END)                             AS OT_Employees
FROM hr_data
GROUP BY Department;

 * mysql+mysqlconnector://root:***@localhost/test
0 rows affected.

[]

In [54]:
%%sql
-- Verify all 3 views created
SHOW FULL TABLES IN hr_analytics WHERE TABLE_TYPE = 'VIEW';

 * mysql+mysqlconnector://root:***@localhost/test
3 rows affected.

[('vw_dept_summary', 'VIEW'),
 ('vw_hr_main', 'VIEW'),
 ('vw_kpi_summary', 'VIEW')]

In [55]:
%%sql
-- Test main view
SELECT * FROM vw_hr_main LIMIT 5;

 * mysql+mysqlconnector://root:***@localhost/test
5 rows affected.

[(1, 41, '36-45', 'Female', 'Single', 'Sales', 'Sales Executive', 2, 5993, 'Medium (3K-6K)', 11, 4, 2, 1, 1, 'Yes', 'Travel_Rarely', 1, 8, '6-10 Years', 6, 4, 0, 5, 0, 3, 'College', 'Life Sciences', 'Yes', 'LOW RISK'),
 (2, 49, '46-55', 'Male', 'Married', 'Research & Development', 'Research Scientist', 2, 5130, 'Medium (3K-6K)', 23, 2, 3, 4, 3, 'No', 'Travel_Frequently', 8, 10, '6-10 Years', 10, 7, 1, 7, 3, 4, 'Below College', 'Life Sciences', 'No', 'LOW RISK'),
 (4, 37, '36-45', 'Male', 'Single', 'Research & Development', 'Laboratory Technician', 1, 2090, 'Low (<3K)', 15, 3, 4, 2, 3, 'Yes', 'Travel_Rarely', 2, 7, '6-10 Years', 0, 0, 0, 0, 3, 3, 'College', 'Other', 'Yes', 'MEDIUM RISK'),
 (5, 33, '26-35', 'Female', 'Married', 'Research & Development', 'Research Scientist', 1, 2909, 'Low (<3K)', 11, 3, 4, 3, 3, 'Yes', 'Travel_Frequently', 3, 8, '6-10 Years', 8, 7, 3, 0, 3, 3, 'Master', 'Life Sciences', 'No', 'MEDIUM RISK'),
 (7, 27, '26-35', 'Male', 'Married', 'Research & Development', 'Laboratory Technician', 1, 3468, 'Medium (3K-6K)', 12, 2, 1, 4, 3, 'No', 'Travel_Rarely', 2, 6, '6-10 Years', 2, 2, 2, 2, 3, 3, 'Below College', 'Medical', 'No', 'LOW RISK')]

In [56]:
%%sql
-- Test KPI view
SELECT * FROM vw_kpi_summary;

 * mysql+mysqlconnector://root:***@localhost/test
1 rows affected.

[(1470, Decimal('237'), Decimal('1233'), Decimal('16.12'), Decimal('36.9'), Decimal('6503'), Decimal('2.73'), Decimal('7.0'), Decimal('416'))]

##  Step 12: Key Business Insights Summary

In [57]:
# Print all key findings
print("=" * 60)
print("   HR ANALYTICS - KEY BUSINESS INSIGHTS")
print("=" * 60)
print()
print("📊 OVERALL:")
print("   • Total Employees     : 1,470")
print("   • Total Attrition     : 237 employees")
print("   • Attrition Rate      : 16.1%")
print("   • Avg Monthly Income  : $6,503")
print("   • Avg Job Satisfaction: 2.73 / 4.0")
print()
print("📉 ATTRITION INSIGHTS:")
print("   • Sales dept has highest attrition  : 20.6%")
print("   • R&D dept has lowest attrition     : 13.8%")
print("   • Overtime employees attrition      : 30.5%")
print("   • Non-overtime employees attrition  : 10.4%")
print("   • Low salary band attrition         : 46.2%")
print("   • Age group 18-25 attrition         : 38.6%")
print("   • Single employees attrition        : 25.5%")
print()
print("💡 RECOMMENDATIONS:")
print("   1. Limit overtime in Sales & R&D departments")
print("   2. Revise salary for Low band employees")
print("   3. Create career growth plans for age 18-25")
print("   4. Regular promotion review every 2 years")
print("   5. Improve job satisfaction in HR department")
print()
print("=" * 60)
print("✅ SQL Analysis Complete! Now open Power BI Desktop")
print("   Connect to: vw_hr_main view in hr_analytics DB")
print("=" * 60)

============================================================
   HR ANALYTICS - KEY BUSINESS INSIGHTS
============================================================

📊 OVERALL:
   • Total Employees     : 1,470
   • Total Attrition     : 237 employees
   • Attrition Rate      : 16.1%
   • Avg Monthly Income  : $6,503
   • Avg Job Satisfaction: 2.73 / 4.0

📉 ATTRITION INSIGHTS:
   • Sales dept has highest attrition  : 20.6%
   • R&D dept has lowest attrition     : 13.8%
   • Overtime employees attrition      : 30.5%
   • Non-overtime employees attrition  : 10.4%
   • Low salary band attrition         : 46.2%
   • Age group 18-25 attrition         : 38.6%
   • Single employees attrition        : 25.5%

💡 RECOMMENDATIONS:
   1. Limit overtime in Sales & R&D departments
   2. Revise salary for Low band employees
   3. Create career growth plans for age 18-25
   4. Regular promotion review every 2 years
   5. Improve job satisfaction in HR department

============================================================
✅ SQL Analysis Complete! Now open Power BI Desktop
   Connect to: vw_hr_main view in hr_analytics DB
============================================================